Checked Exceptions

IOException
FileNotFoundException
SQLException
ClassNotFoundException
InterruptedException
NoSuchMethodException
InstantiationException
MalformedURLException
RemoteException
CloneNotSupportedException

Unchecked Exceptions

NullPointerException
ArrayIndexOutOfBoundsException
ArithmeticException
IllegalArgumentException
IllegalStateException
NumberFormatException  : string to int
ClassCastException : converting from narrow casting , object to int : (object is also string).
IndexOutOfBoundsException 
UnsupportedOperationException
SecurityException





Exception : unwanted situation that occured during runtime called exception.if exception not handled then next step of the program wont get excecuted
why need to do exception ?
To run our code util end , we need to do exception.

try : that might have exception
catch : that handle exception 
finally{ } : print statement , with or without exception it will do its operation.
throw : throws an exception
throws : method that may contain exception.
checkedException : 
*) ArithematicException 
class Main {
    public static void main(String[] args) {
        int a = 5;

        for (int b = 0; b < 5; b++) {
            try{
                int c = a/b;
                System.out.println("Result of " + a + "/" + b + " = " + c);
        }catch(Exception e){
            System.out.println(e);  // just by saying this much it will handle it ,by catch(Exception e) also handle exception no need of new method.
        }
        }
    }
}
*) NullPointerException 
class Main{
    public static void main(String[] args){
        String str1 = "vinay";
        String str2 = null; //  null value
        String str3 = "hello";
     str1 = str1.toUpperCase();
     System.out.println(str1);
     try{
     str2 = str2.toUpperCase();
     System.out.println(str2);
     }catch(NullPointerException e){
         System.out.println("Null value cannot connverted to uppercase");
     }
     str3 = str3.toUpperCase();
     System.out.println(str3);
    }
} 
output : 
VINAY
Null value cannot connverted to uppercase
HELLO

*)NumberFormatException

class Main{
    public static void main(String[] args){
        String str = "vinay";
        String str1 = "1382";
        int b = Integer.parseInt(str1);
    
        System.out.println(b);
        try{
        int a = Integer.parseInt(str);
    }catch(NumberFormatException e){
        System.out.println("String vinay cannot convert to Integer");
    }
}
}

output : 
1382
String vinay cannot convert to Integer

*) ArrayIndexOutOfBoundsException 

class Main{
    public static void main(String[] args){
        int[] arr = {1,2,3,4,5};
        System.out.println(arr[2]);
        try{
        System.out.println(arr[8]);
    }catch(ArrayIndexOutOfBoundsException e ){
        System.out.println("Index value not found");
    }
    System.out.println(arr[4]);
    }
}

*)IllegalargumentException 
if a = -1 ,(age<0) throw "illegalException " : only when if condition are applied then we can use this.
*)IllegalThreadStatexception 
calling two thread with same objcet.

*)IndexOutOfBoundsException 
import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        ArrayList<String> list = new ArrayList<>();
        list.add("apple");
        list.add("banana");
        try{
        System.out.print(list.get(2));
        // Check if the index is within the bounds of the list
    }catch(IndexOutOfBoundsException e){
        
    }
    }
}

CHECKED EXCEPTION 
*)ClassNotFoundException 
class Main{
    public static void main(String[] args){
        try{
        Class.forName("one.java");
    }catch(ClassNotFoundException e){
        System.out.println("class one.java Not found");
    }
    System.out.println("Hi");
}
}

*)FileNotFoundException
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
class Main{
    public static void main(String[] args){
        try{
        File file = new File("one.txt");
        Scanner sc = new Scanner(file);
    }catch(FileNotFoundException e ){
        System.out.println("file not there");
    }
}
}

*)InterruptedException  : MultipleThreads.
*)IOException 
import java.io.FileWriter;
import java.io.IOException;
class Main{
    public static void main(String[] args){
        try{
        FileWriter Writer = new FileWriter("exam.txt");
        Writer.write("Hello");
        Writer.close();
    }catch(IOException e){
        System.out.println("file cannot write it");
    }
}
}
*)
